<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="0" total="8" passed="4">
  <reporter-output>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
    </line>
  </reporter-output>
  <suite name="Functional Suite" duration-ms="697" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:06 IST">
    <groups>
      <group name="bvt">
        <method signature="TestCase3.fourthTest()[pri:4, instance:testcases.TestCase3@5579bb86]" name="fourthTest" class="testcases.TestCase3"/>
      </group> <!-- bvt -->
      <group name="functional">
        <method signature="TestCase1.doLogin()[pri:2, instance:testcases.TestCase1@a74868d]" name="doLogin" class="testcases.TestCase1"/>
        <method signature="TestCase1.doUserReg()[pri:1, instance:testcases.TestCase1@a74868d]" name="doUserReg" class="testcases.TestCase1"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@5579bb86]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@5579bb86]" name="doLogin" class="testcases.TestCase3"/>
        <method signature="TestCase3.thirdTest()[pri:3, instance:testcases.TestCase3@5579bb86]" name="thirdTest" class="testcases.TestCase3"/>
      </group> <!-- functional -->
      <group name="smoke">
        <method signature="TestCase2.validateTitles()[pri:0, instance:testcases.TestCase2@4c762604]" name="validateTitles" class="testcases.TestCase2"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@5579bb86]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@5579bb86]" name="doLogin" class="testcases.TestCase3"/>
        <method signature="TestCase3.thirdTest()[pri:3, instance:testcases.TestCase3@5579bb86]" name="thirdTest" class="testcases.TestCase3"/>
      </group> <!-- smoke -->
    </groups>
    <test name=" Login Test" duration-ms="245" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
      <class name="testcases.TestCase1">
        <test-method status="PASS" signature="createDBConn()[pri:0, instance:testcases.TestCase1@a74868d]" name="createDBConn" is-config="true" duration-ms="2" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDBConn -->
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:testcases.TestCase1@a74868d]" name="LaunchBrowser" is-config="true" duration-ms="1" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testcases.TestCase1@a74868d]" name="doUserReg" duration-ms="35" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@a74868d]" name="closeBrowser" is-config="true" duration-ms="3" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:testcases.TestCase1@a74868d]" name="LaunchBrowser" is-config="true" duration-ms="4" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testcases.TestCase1@a74868d]" name="doLogin" duration-ms="33" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@a74868d]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDBConn()[pri:0, instance:testcases.TestCase1@a74868d]" name="closeDBConn" is-config="true" duration-ms="1" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- testcases.TestCase1 -->
    </test> <!--  Login Test -->
    <test name="Validate Titles" duration-ms="47" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
      <class name="testcases.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testcases.TestCase2@4c762604]" name="validateTitles" duration-ms="13" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Title does not match expected [gmail.com] but found [yahoo.com],
Text does not match expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Title does not match expected [gmail.com] but found [yahoo.com],
Text does not match expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.TestCase2.validateTitles(TestCase2.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testcases.TestCase2 -->
    </test> <!-- Validate Titles -->
    <test name="Dependency Test" duration-ms="79" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
      <class name="testcases.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testcases.TestCase3@5579bb86]" name="doUserReg" duration-ms="4" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User reg failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User reg failed
at org.testng.Assert.fail(Assert.java:97)
at testcases.TestCase3.doUserReg(TestCase3.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testcases.TestCase3@5579bb86]" name="doLogin" duration-ms="1" started-at="2020-09-03T11:45:06 IST" depends-on-methods="testcases.TestCase3.doUserReg" finished-at="2020-09-03T11:45:06 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@5579bb86] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@5579bb86] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="thirdTest()[pri:3, instance:testcases.TestCase3@5579bb86]" name="thirdTest" duration-ms="6" started-at="2020-09-03T11:45:06 IST" depends-on-methods="testcases.TestCase3.doUserReg" finished-at="2020-09-03T11:45:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method status="PASS" signature="fourthTest()[pri:4, instance:testcases.TestCase3@5579bb86]" name="fourthTest" duration-ms="5" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
      </class> <!-- testcases.TestCase3 -->
    </test> <!-- Dependency Test -->
    <test name="Failure Test" duration-ms="9" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
      <class name="testcases.TestFailure">
        <test-method status="FAIL" signature="doLogin()[pri:0, instance:testcases.TestFailure@6fb0d3ed]" name="doLogin" duration-ms="2" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing the login test
at org.testng.Assert.fail(Assert.java:97)
at testcases.TestFailure.doLogin(TestFailure.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\Docker-Con2.jpg" target="_blank"><img height=200 width=200 src="C:\Users\Docker-Con2.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doLogin -->
      </class> <!-- testcases.TestFailure -->
      <class name="testcases.TestCase3">
        <test-method status="PASS" signature="setup()[pri:0, instance:testcases.TestCase3@5579bb86]" name="setup" is-config="true" duration-ms="21" started-at="2020-09-03T11:45:05 IST" finished-at="2020-09-03T11:45:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TestCase3@5579bb86]" name="tearDown" is-config="true" duration-ms="1" started-at="2020-09-03T11:45:06 IST" finished-at="2020-09-03T11:45:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TestCase3 -->
    </test> <!-- Failure Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
